const mongoose = require('mongoose');
const bcrypt = require('bcrypt');

const userSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Please enter your name'],
  },
  email: {
    type: String,
    unique: true,
    required: [true, 'Please provide your email'],
  },
  password: {
    type: String,
    required: [true, 'Please provide your password'],
    minlength: 4,
  },
});

userSchema.methods.matchPassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

// middleware
userSchema.pre('save', async function (next) {
  if (!this.isModified('password')) {
    next();
  }

  const salt = await bcrypt.genSalt(5);
  this.password = await bcrypt.hash(this.password, salt);
  // hash generated by bcrypt is not just hash but hash and salt concatenated
});

const User = mongoose.model('User', userSchema);

module.exports = User;
